---
# tasks file for docker

- name: install dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_dependencies }}"
  tags: install

- name: add docker GPG key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
  tags: install

- name: add docker repo to apt sources
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  register: apt_repository
  tags: install

- name: update apt cache
  become: true
  when: apt_repository.changed
  apt:
    update_cache: true
  tags: install

- name: install docker
  become: true
  apt:
    name: "{{ docker_package }}"
    state: present
  tags: install

- name: ensure docker is started and enabled
  become: true
  systemd:
    name: docker
    state: started
    enabled: true
  tags: install
